[package]
name = "data_frost"
version = "0.1.0"
edition = "2021"

[dependencies]
mutability_marker = { version = "0.1.1", default-features = false }
task_pool = { version = "0.1.4", default-features = false }